name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # This workflow will run when you push to the main branch
  pull_request:
    branches:
      - main  # This workflow will also run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gcp-deployment:latest
            ghcr.io/${{ github.repository_owner }}/gcp-deployment:${{ github.sha }}

      - name: Image digest
        run: echo "Image digest: ${{ steps.docker_meta.outputs.digest }}"
